// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCw_6_nyW4RwvQEONtPkr8THZ9UlzkV40',
    appId: '1:962609104022:web:b1655fe7b627828c136eb7',
    messagingSenderId: '962609104022',
    projectId: 'sia-sekolah-14e9d',
    authDomain: 'sia-sekolah-14e9d.firebaseapp.com',
    storageBucket: 'sia-sekolah-14e9d.firebasestorage.app',
    measurementId: 'G-9KFMFLGMKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALuVAG4ojsb3XCZPPsoM_r-nqU3bb71vo',
    appId: '1:962609104022:android:f7d81341f33cc4bc136eb7',
    messagingSenderId: '962609104022',
    projectId: 'sia-sekolah-14e9d',
    storageBucket: 'sia-sekolah-14e9d.firebasestorage.app',
  );
}
